#!/bin/bash
app=gogs

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Generate random password
db_pwd=$(openssl rand -hex 15)

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $app -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd
# sudo yunohost app setting $app adminusername -v $admin

# install gogs
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo useradd -d $final_path $app
sudo cp -a ../sources/* $final_path

# copy init script
sudo cp $final_path/scripts/init/debian/gogs /etc/init.d
sudo chown root:root /etc/init.d/gogs
sudo chmod +x /etc/init.d/gogs

# repository path
repo_path=/home/yunohost.app/$app
sudo mkdir -p $repo_path
sudo yunohost app setting $app repopath -v $repo_path

# Generate random key
key=$(openssl rand -hex 15)

# Copy and edit app.ini
sudo mkdir -p $final_path/custom/conf
sudo cp ../conf/app.ini $final_path/custom/conf/app.ini
sudo sed -i "s@yuno_repo@$repo_path@g" $final_path/custom/conf/app.ini
sudo sed -i "s@yuno_url@$domain$path@g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_dbpdw/$db_pwd/g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_dbuser/$app/g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_domain/$domain/g" $final_path/custom/conf/app.ini
sudo sed -i "s/yuno_key/$key/g" $final_path/custom/conf/app.ini

# set correct permissions
sudo chown -hR gogs: $final_path
sudo chown -hR gogs: $repo_path

# Add Gogs to YunoHost's monitored services
sudo yunohost service add gogs --log /var/log/gogs.log

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
# sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

sudo service gogs restart

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf

# TODO
# admin=$3
# Retrieve admin email
# email=$(sudo yunohost user info $admin | grep mail: | sed "s/mail: //g")
# password=$4
# install with curl and parameter for $admin / $password / $email
# after install launch sql script to activate ldap auth see ../conf/login_source.sql (not working config)
