#!/bin/bash
app=gogs

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
root_pwd=$(sudo cat /etc/yunohost/mysql)

sudo service gogs stop

# Get installation paths
install_path=$(sudo yunohost app setting $app install_path)
source_path=$(sudo yunohost app setting $app source_path)

# Remove data
repo_path=$(sudo yunohost app setting $app repopath)
sudo rm -rf $repo_path

# Remove init script
if [[ $(cat /etc/debian_version) = "7."* ]]
then
	sudo update-rc.d gogs remove
else
	sudo systemctl disable gogs.service
	sudo rm -rf /etc/systemd/system/gogs.service
	sudo systemctl daemon-reload
fi

# Remove app
sudo rm -rf $install_path
sudo rm -rf $source_path
sudo rm -rf /etc/ini.d/gogs
sudo rm -rf /etc/logrotate.d/gogs
sudo service rsyslog restart
sudo rm -rf /var/log/gogs
sudo userdel gogs
sudo rm -rf /home/gogs

# Remove home directory
sudo rm -rf /home/yunohost.app/gogs

# Remove database
mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"

# Remove monitor
sudo yunohost service remove gogs 

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf