#!/bin/bash
app=gogs

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
root_pwd=$(sudo cat /etc/yunohost/mysql)

sudo service gogs stop

# Remove data
data_path=$(sudo yunohost app setting $app datapath)
sudo rm -rf $data_path

# Remove init script
sudo systemctl disable gogs.service
sudo rm -rf /etc/systemd/system/gogs.service
sudo systemctl daemon-reload

# Remove app
final_path=/opt/$app
sudo rm -rf $final_path
sudo rm -rf /etc/logrotate.d/gogs
sudo service rsyslog restart
sudo rm -rf /var/log/gogs
sudo userdel gogs
sudo rm -rf /home/gogs

# Remove database
mysql -u root -p$root_pwd -e "DROP DATABASE $app ; DROP USER $app@localhost ;"

# Remove monitor
sudo yunohost service remove gogs

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
